<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE businesscards
[
    <!ELEMENT businesscards(individual+)>
    <!ELEMENT individual (Personname,contact)>
    <!ELEMENT Personname (#PCDATA)>
    <!ELEMENT contact (#PCDATA)>
    <!ATTLIST contact (home | work | mobile | email)>
]>
<bussinesscards>
<individual>
<Personname>Rorie Demanche</Personname>
<contact type= "home">+1 (710) 153-4949</contact>
<contact type= "work">+1 (503) 319-3558</contact>
<contact type= "mobile">+1 (182) 748-1667</contact>
<contact type= "email">rdemanche0@foxnews.com</contact>
</individual>

<individual>
<Personname>Kelcey Surman</Personname>
<contact type= "home">+1 (249) 926-7376</contact>
<contact type= "work">+1 (208) 363-6588</contact>
<contact type= "mobile">+1 (982) 536-6860 </contact>
<contact type= "email">ksurman1@usnews.com</contact>
</individual>

<individual>
<Personname>Simon Heddan</Personname>
<contact type= "home">+1 (687) 808-4290</contact>
<contact type= "work">+1 (604) 815-7810</contact>
<contact type= "mobile">+1 (924) 174-3271 </contact>
<contact type= "email">sheddan2@alexa.com</contact>
</individual>

<individual>
<Personname>Chan Supple</Personname>
<contact type= "home">+1 (577) 165-2495</contact>
<contact type= "work">+1 (547) 934-7337 </contact>
<contact type= "mobile">+1 (367) 667-0747</contact>
<contact type= "email">csupple3@123-reg.co.uk</contact>
</individual>
</bussinesscards>








